language: php

php:
  - 7.0

script:
  - tests/bin/coverage.sh

before_script:
  - phpenv config-add tests/php.ini
  - composer install

after_script:
  wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && php coveralls.phar --verbose --config tests/.coveralls.yml